CREATE TABLE IF NOT EXISTS  categories(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    user_id BIGSERIAL REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
)