CREATE TABLE comments(
    id BIGSERIAL PRIMARY KEY,
    body TEXT NOT NULL,
    user_id BIGSERIAL REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    meetup_id BIGSERIAL REFERENCES meetups (id) ON DELETE CASCADE NOT NULL,
    parent_id BIGSERIAL REFERENCES comments (id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
)