CREATE TABLE conversations(
    id BIGSERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    user_id BIGSERIAL REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    parent_id BIGSERIAL REFERENCES comments (id) ON DELETE CASCADE NOT NULL,
    last_reply TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
)